line-length = 100
target-version = "py314"

[lint]
select = ["E", "F", "I", "N", "UP", "B", "TRY", "RUF"]
ignore = [
    "BLE001",
    "S110",
    "TRY401",
    "TRY003",
    "TRY400",
    "E731",
    "B027",
    "UP046",
    "UP042",
]
